// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCit6uO1Jg21YQHVLhQgv9SXIrmpEvh44A',
    appId: '1:357420401265:web:bed9548ff9a0489a92d1d0',
    messagingSenderId: '357420401265',
    projectId: 'ddip-fd9f8',
    authDomain: 'ddip-fd9f8.firebaseapp.com',
    storageBucket: 'ddip-fd9f8.firebasestorage.app',
    measurementId: 'G-YP3F7CHG00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCF2AZt2lC17ltfIVDvmTZ69fzpw1blyo',
    appId: '1:357420401265:android:7bd2889cbb3b650792d1d0',
    messagingSenderId: '357420401265',
    projectId: 'ddip-fd9f8',
    storageBucket: 'ddip-fd9f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZHUEqH2gzO8P9-QAdpMrPfjQwulMjKeI',
    appId: '1:357420401265:ios:833d0f8365308f9492d1d0',
    messagingSenderId: '357420401265',
    projectId: 'ddip-fd9f8',
    storageBucket: 'ddip-fd9f8.firebasestorage.app',
    iosClientId: '357420401265-tm84f3f8au3oajvoc3s2f0jihs8p3b36.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddip',
  );
}
